package it.polimi.ingsw.controller.commands;

public enum CommandName {

    LOGIN,
    PONG,
    QUIT,
    SET_SIZE,
    UNKNOWN,
    INITIALISE_LEADER_CARDS,
    INITIALISE_RESOURCES,
    ACTIVATE_CARD,
    DISCARD_CARD,
    LEADER_ACTION,
    BUY_CARD,
    SELECT_POSITION,
    SELECT_RESOURCES_FROM_WAREHOUSE,
    CHOOSE_LEADER_CARDS,
    CHOOSE_MARBLES,
    INSERT_IN_WAREHOUSE,
    PRODUCTION,
    BASIC_PRODUCTION,
    NORMAL_PRODUCTION,
    LEADER_PRODUCTION,
    END_PRODUCTION,
    END_TURN,
    SHIFT_RESOURCES

}
